### ISSUE TITLE
can't change the brightness of the monitor or laptop screen

### ISSUE THREAD

**Issue by javadmahmoodi670** [rsdev69/ThinkPad-E560-Hackintosh#35]
Hello.  I can't change the brightness of the monitor or laptop screen after updating the Mac and replacing the efi file you sent me, and their options are disabled.  
Also, after locking the screen, the screen turns black and you can no longer enter the password and enter the Mac environment.  And I have to turn the system on and off again.
please help.

![image](https://user-images.githubusercontent.com/77070621/121841672-0ac98e80-ccf4-11eb-8068-53e5e20995aa.jpeg)

![image](https://user-images.githubusercontent.com/77070621/121841720-27fe5d00-ccf4-11eb-840f-b379f7801149.jpeg)

**Comment by rsdev69** [comment]
> Hello. I can't change the brightness of the monitor or laptop screen after updating the Mac and replacing the efi file you sent me, and their options are disabled.
> Also, after locking the screen, the screen turns black and you can no longer enter the password and enter the Mac environment. And I have to turn the system on and off again.
> please help.

Try this files.
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6646767/EFI.zip)

**Comment by javadmahmoodi670** [comment]
> > Hello. I can't change the brightness of the monitor or laptop screen after updating the Mac and replacing the efi file you sent me, and their options are disabled.
> 
> > Also, after locking the screen, the screen turns black and you can no longer enter the password and enter the Mac environment. And I have to turn the system on and off again.
> 
> > please help.
> 
> 
> 
> Try this files.
> 
> [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6646767/EFI.zip)
> 
> 

I replaced it but the problem did not go away

![image](https://user-images.githubusercontent.com/77070621/121868197-eed6e480-cd15-11eb-8f99-e09897b694d6.jpeg)

**Comment by rsdev69** [comment]
> I replaced it but the problem did not go away
> and Turning Bluetooth on and off is also disabled

I think the problem in macOs 11.4
Before brightness work fine.
I don't know how fix this problem.

**Comment by javadmahmoodi670** [comment]
> > I replaced it but the problem did not go away
> 
> > and Turning Bluetooth on and off is also disabled
> 
> 
> 
> I think the problem in macOs 11.4
> 
> Before brightness work fine.
> 
> I don't know how fix this problem.
> 
> 

If you do not know how to solve this problem, then no one knows ‌ and my problem will not be solved 😢

**Comment by rsdev69** [comment]
> If you do not know how to solve this problem, then no one knows ‌ and my problem will not be solved 😢

Try files from releases older > OpenCore 0.7.0
https://github.com/rsdev69/ThinkPad-E560-Hackintosh/releases
Maybe I'm wrong somewhere in the config with new updates.

**Comment by javadmahmoodi670** [comment]
> > If you do not know how to solve this problem, then no one knows ‌ and my problem will not be solved 😢
> 
> 
> 
> Try files from releases older > OpenCore 0.7.0
> 
> https://github.com/rsdev69/ThinkPad-E560-Hackintosh/releases
> 
> Maybe I'm wrong somewhere in the config with new updates.

I'm really confused.  I do not know which version to use.  Please help me solve my problem

**Comment by rsdev69** [comment]
> I'm really confused. I do not know which version to use. Please help me solve my problem

I no longer have ThinkPad E560. Update this repository makes no sense.

**Comment by javadmahmoodi** [comment]
> > I'm really confused. I do not know which version to use. Please help me solve my problem
> 
> I no longer have ThinkPad E560. Update this repository makes no sense.

Can you tell me how I should do this myself and extend the efi file for the e560 laptop to fix my problem?

**Comment by rsdev69** [comment]
For graphics and backlight enable responsible SSDT-PNLF.aml and WhateverGreen.kext 
Maybe in new OpenCore updated dsdt tables and the old method backlight enable no longer works.

**Comment by rsdev69** [comment]
> Can you tell me how I should do this myself and extend the efi file for the e560 laptop to fix my problem?

For graphics and backlight enable responsible SSDT-PNLF.aml and WhateverGreen.kext
Maybe in new OpenCore updated dsdt tables and the old method backlight enable no longer works.

**Comment by javadmahmoodi670** [comment]
> > Can you tell me how I should do this myself and extend the efi file for the e560 laptop to fix my problem?
> 
> 
> 
> For graphics and backlight enable responsible SSDT-PNLF.aml and WhateverGreen.kext
> 
> Maybe in new OpenCore updated dsdt tables and the old method backlight enable no longer works.

What program should I edit or modify these files with?

**Comment by rsdev69** [comment]
> What program should I edit or modify these files with?

I dont know. I updated only files OpenCore.
I used tables DSDT from this repo https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore
This repo has a similar hardware.

**Comment by javadmahmoodi670** [comment]
> > What program should I edit or modify these files with?
> 
> 
> 
> I dont know. I updated only files OpenCore.
> 
> I used tables DSDT from this repo https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore
> 
> This repo has a similar hardware.
> 
> 

Hello.  I could not do this properly.  As a result, I had to format my laptop hard drive and reinstall my Mac.  But when I put the flash boot Mac that was working properly, I get the following error.  Please help us to solve the problem

![image](https://user-images.githubusercontent.com/77070621/122401233-a9bee680-cf91-11eb-8a48-9a4141af0508.jpeg)

**Comment by rsdev69** [comment]
> Hello. I could not do this properly. As a result, I had to format my laptop hard drive and reinstall my Mac. But when I put the flash boot Mac that was working properly, I get the following error. Please help us to solve the problem

After install MacOs, BigSur make snapshots of your disk. This is problem.
You have 2 options.
1. Install Windows installer on usb, boot in install and format disk.
2. Install MacOs installer on usb, boot in install and format disk from diskutil with this command 
**diskutil partitionDisk disk1 MBR "MS-DOS FAT32" EXTDRIVE 0b**

**Comment by javadmahmoodi670** [comment]
> > Hello. I could not do this properly. As a result, I had to format my laptop hard drive and reinstall my Mac. But when I put the flash boot Mac that was working properly, I get the following error. Please help us to solve the problem
> 
> 
> 
> After install MacOs, BigSur make snapshots of your disk. This is problem.
> 
> You have 2 options.
> 
> 1. Install Windows installer on usb, boot in install and format disk.
> 
> 2. Install MacOs installer on usb, boot in install and format disk from diskutil with this command 
> 
> **diskutil partitionDisk disk1 MBR "MS-DOS FAT32" EXTDRIVE 0b**
> 
> 
> 
> 

I have already made Flash Boot for Mac and Flash Boot for Windows installation.  But I do not know why I get a high error when I connect the flash boot Mac to the laptop.  What should I do now?  It only recognizes the Windows installation boot flash and I can install Windows with the flash boot

**Comment by rsdev69** [comment]
> I have already made Flash Boot for Mac and Flash Boot for Windows installation. But I do not know why I get a high error when I connect the flash boot Mac to the laptop. What should I do now? It only recognizes the Windows installation boot flash and I can install Windows with the flash boot

Possibly broken image.
Try install Catalina. It is lighter and no problems with this system.

**Comment by javadmahmoodi670** [comment]
> > I have already made Flash Boot for Mac and Flash Boot for Windows installation. But I do not know why I get a high error when I connect the flash boot Mac to the laptop. What should I do now? It only recognizes the Windows installation boot flash and I can install Windows with the flash boot
> 
> 
> 
> Possibly broken image.
> 
> Try install Catalina. It is lighter and no problems with this system.

Now that I do not have a Mac operating system, how can I make Flash Boot for Catalina with Windows ?!

**Comment by rsdev69** [comment]
> Now that I do not have a Mac operating system, how can I make Flash Boot for Catalina with Windows ?!

Yes, BDU Make bootable USB Flash Disk for macOS in Windows
http://cvad-mac.narod.ru/index/bootdiskutility_exe/0-5

**Comment by javadmahmoodi670** [comment]
> > Now that I do not have a Mac operating system, how can I make Flash Boot for Catalina with Windows ?!
> 
> 
> 
> Yes, BDU Make bootable USB Flash Disk for macOS in Windows
> 
> http://cvad-mac.narod.ru/index/bootdiskutility_exe/0-5
> 
> 

thanks a lot.  Only from which link should I download McCatalina or Big Shore so that I can make a flash boot with this program that you introduced?

**Comment by rsdev69** [comment]
> thanks a lot. Only from which link should I download McCatalina or Big Shore so that I can make a flash boot with this program that you introduced?

This utility download latest macOs.
On site has tutorial how to use this utility.

**Comment by javadmahmoodi670** [comment]
> > thanks a lot. Only from which link should I download McCatalina or Big Shore so that I can make a flash boot with this program that you introduced?
> 
> 
> 
> This utility download latest macOs.
> 
> On site has tutorial how to use this utility.

I made the flash boot in Windows according to the tutorial.  But when I boot, after displaying the clover screen and tapping the Mac option, I encounter a black screen that has been the same for several hours and has not changed.  please guide me.

**Comment by rsdev69** [comment]
> I made the flash boot in Windows according to the tutorial. But when I boot, after displaying the clover screen and tapping the Mac option, I encounter a black screen that has been the same for several hours and has not changed. please guide me.

Replace EFI folder in usb on my
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6673297/EFI.zip)

**Comment by javadmahmoodi670** [comment]
> > I made the flash boot in Windows according to the tutorial. But when I boot, after displaying the clover screen and tapping the Mac option, I encounter a black screen that has been the same for several hours and has not changed. please guide me.
> 
> 
> 
> Replace EFI folder in usb on my
> 
> [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6673297/EFI.zip)
> 
> 
> 
> 

Thankful.  I was able to install Mac.  But the flash boot must be connected to the laptop so I can log in to the Mac.  I replaced the original Mac efi with the this efi folder.  But I still have to enter the Mac with the arrow.  How do I fix this?

**Comment by rsdev69** [comment]
> But I still have to enter the Mac with the arrow. How do I fix this?

I did not understand what an arrow?

**Comment by javadmahmoodi670** [comment]
> > But I still have to enter the Mac with the arrow. How do I fix this?
> 
> 
> 
> I did not understand what an arrow?
> 
> 
> 
> 

The problem now is that I can't log in to the Mac without the flash boot I made.  I must connect the flash boot to the laptop.  How do I fix this problem?

**Comment by rsdev69** [comment]
> The problem now is that I can't log in to the Mac without the flash boot I made. I must connect the flash boot to the laptop. How do I fix this problem?

https://www.youtube.com/watch?v=LgAp4yiNQCw&ab_channel=Linuxfornewbie
After replace EFI on your EFI folder.

**Comment by javadmahmoodi670** [comment]
> > The problem now is that I can't log in to the Mac without the flash boot I made. I must connect the flash boot to the laptop. How do I fix this problem?
> 
> 
> 
> https://www.youtube.com/watch?v=LgAp4yiNQCw&ab_channel=Linuxfornewbie
> 
> After replace EFI on your EFI folder.
> 
> 

Do I have to replace the last efi file you gave me?

**Comment by rsdev69** [comment]
> Do I have to replace the last efi file you gave me?

Yes, replace.

**Comment by javadmahmoodi670** [comment]
> > Do I have to replace the last efi file you gave me?
> 
> 
> 
> Yes, replace.

After installing Mac Catalania, I came up with a new version of the MAC Big Sur on the flash boot.  Now when I restart the system, I got the following error and I can not install the new Mac version of the flash boot.

![image](https://user-images.githubusercontent.com/77070621/122545511-2b228180-d043-11eb-90e0-d5729e3de873.jpeg)

**Comment by rsdev69** [comment]
> After installing Mac Catalania, I came up with a new version of the MAC Big Sur on the flash boot. Now when I restart the system, I got the following error and I can not install the new Mac version of the flash boot.

Stay on Catalina. Big Sur work bad on laptop.

**Comment by javadmahmoodi670** [comment]
> > After installing Mac Catalania, I came up with a new version of the MAC Big Sur on the flash boot. Now when I restart the system, I got the following error and I can not install the new Mac version of the flash boot.
> 
> 
> 
> Stay on Catalina. Big Sur work bad on laptop.
> 
> 

I need a new version of Big Sur to code in the new XCode environment.  Can this error be fixed?  What is the solution?

**Comment by rsdev69** [comment]
> I need a new version of Big Sur to code in the new XCode environment. Can this error be fixed? What is the solution?

You're going to have to do this part yourself.
If you want to use macOS read OpenCore Guide and try to install.
https://dortania.github.io/OpenCore-Install-Guide/

**Comment by javadmahmoodi670** [comment]
> > I need a new version of Big Sur to code in the new XCode environment. Can this error be fixed? What is the solution?
> 
> 
> 
> You're going to have to do this part yourself.
> 
> If you want to use macOS read OpenCore Guide and try to install.
> 
> https://dortania.github.io/OpenCore-Install-Guide/
> 
> 

I was able to reinstall big sur after many difficulties.  I hope you will solve the problem of the screen brightness not working in the next version of the efi file.

**Comment by rsdev69** [comment]
> I was able to reinstall big sur after many difficulties. I hope you will solve the problem of the screen brightness not working in the next version of the efi file.

I update repo to OpenCore 0.7.1
Test it, and say as a result.

**Comment by javadmahmoodi** [comment]
> > I was able to reinstall big sur after many difficulties. I hope you will solve the problem of the screen brightness not working in the next version of the efi file.
> 
> I update repo to OpenCore 0.7.1
> Test it, and say as a result.

Unfortunately, the problem has not been resolved and it is still not possible to increase or decrease the screen brightness

**Comment by rsdev69** [comment]
> Unfortunately, the problem has not been resolved and it is still not possible to increase or decrease the screen brightness

Good news! I fixed the screen backlight, everything works 100%
![Screenshot 2021-07-11 at 15 39 13](https://user-images.githubusercontent.com/34169770/125196958-760b6f80-e264-11eb-91b2-165281833c07.png)

**Comment by javadmahmoodi670** [comment]
> > Unfortunately, the problem has not been resolved and it is still not possible to increase or decrease the screen brightness
> 
> 
> 
> Good news! I fixed the screen backlight, everything works 100%
> 
> ![Screenshot 2021-07-11 at 15 39 13](https://user-images.githubusercontent.com/34169770/125196958-760b6f80-e264-11eb-91b2-165281833c07.png)
> 
> 
> 
> 

Hello, thank you. What can I do to fix the problem?

**Comment by rsdev69** [comment]
> > > Unfortunately, the problem has not been resolved and it is still not possible to increase or decrease the screen brightness
> > 
> > 
> > Good news! I fixed the screen backlight, everything works 100%
> > ![Screenshot 2021-07-11 at 15 39 13](https://user-images.githubusercontent.com/34169770/125196958-760b6f80-e264-11eb-91b2-165281833c07.png)
> 
> Hello, thank you. What can I do to fix the problem?

Replace EFI 
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797636/EFI.zip)

**Comment by javadmahmoodi670** [comment]
> > > > Unfortunately, the problem has not been resolved and it is still not possible to increase or decrease the screen brightness
> 
> > > 
> 
> > > 
> 
> > > Good news! I fixed the screen backlight, everything works 100%
> 
> > > ![Screenshot 2021-07-11 at 15 39 13](https://user-images.githubusercontent.com/34169770/125196958-760b6f80-e264-11eb-91b2-165281833c07.png)
> 
> > 
> 
> > Hello, thank you. What can I do to fix the problem?
> 
> 
> 
> Replace EFI 
> 
> [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6797636/EFI.zip)
> 
> 

Unfortunately, the problem persists and this version did not work.  Also, leaving the laptop pad does not work anymore

![image](https://user-images.githubusercontent.com/77070621/125229924-02fa0b80-e2ed-11eb-81ba-cf201ad2c01d.jpeg)

**Comment by rsdev69** [comment]
> Unfortunately, the problem persists and this version did not work. Also, leaving the laptop pad does not work anymore

Everything is working now, i gave the wrong config.
![Screenshot 2021-07-12 at 10 47 24](https://user-images.githubusercontent.com/34169770/125250356-cf27e180-e2fe-11eb-9afe-2dd23eae4fa0.png)
![Screenshot 2021-07-12 at 10 47 09](https://user-images.githubusercontent.com/34169770/125250372-d353ff00-e2fe-11eb-856b-3090c9b54c7b.png)
[EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6799537/EFI.zip)

**Comment by javadmahmoodi670** [comment]
> > Unfortunately, the problem persists and this version did not work. Also, leaving the laptop pad does not work anymore
> 
> 
> 
> Everything is working now, i gave the wrong config.
> 
> ![Screenshot 2021-07-12 at 10 47 24](https://user-images.githubusercontent.com/34169770/125250356-cf27e180-e2fe-11eb-9afe-2dd23eae4fa0.png)
> 
> ![Screenshot 2021-07-12 at 10 47 09](https://user-images.githubusercontent.com/34169770/125250372-d353ff00-e2fe-11eb-856b-3090c9b54c7b.png)
> 
> [EFI.zip](https://github.com/rsdev69/ThinkPad-E560-Hackintosh/files/6799537/EFI.zip)
> 
> 
> 
> 

The laptop trackpad works properly.  But increasing and decreasing the screen is inactive

**Comment by rsdev69** [comment]
> The laptop trackpad works properly. But increasing and decreasing the screen is inactive

This is the maximum opportunities that a trackpad can.

**Comment by javadmahmoodi670** [comment]
> > The laptop trackpad works properly. But increasing and decreasing the screen is inactive
> 
> 
> 
> This is the maximum opportunities that a trackpad can.

The screen light adjustment problem has not been fixed and is still disabled.

**Comment by rsdev69** [comment]
> The screen light adjustment problem has not been fixed and is still disabled.

I have no problem with screen light. I showed screenshots that everything works.
